name: Reusable Python Security

on:
  workflow_call:
    inputs:
      python-version:
        description: "Python version to use"
        required: false
        type: string
        default: "3.13"

jobs:
  py-security:
    name: Python Security Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b

      - name: Set up Python
        run: uv python install ${{ inputs.python-version }}

      - name: Install dependencies
        run: uv sync --group dev

      - name: Run pip-audit
        run: uv run pip-audit

      - name: Run bandit
        run: uv run bandit -r src -ll
